# Generated by Django 4.1 on 2022-09-22 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchItem',
            new_name='MyWatchList',
        ),
    ]
